[package]
name = "documentation-builder"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2018"

[dependencies]
base = { path = "../base" }
documentation = { path = "../documentation" }
roxmltree = "0.14.1"
flate2 = "1.0.22"
tar = "0.4.37"
reqwest = "0.11.4"
itertools = "0.10.1"
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
directories = "4.0.1"
log = "0.4.14"
textwrap = "0.14.2"

[dev-dependencies]
pretty_assertions = "0.7.2"
