[package]
name = "documentation-builder"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2021"

[dependencies]
base = { path = "../base" }
documentation = { path = "../documentation" }
roxmltree = "0.14.1"
flate2 = "1.0.22"
tar = "0.4.38"
reqwest = "0.11.8"
itertools = "0.10.3"
serde_json = "1.0.73"
serde = { version = "1.0.132", features = ["derive"] }
directories = "4.0.1"
log = "0.4.14"
textwrap = "0.14.2"

[dev-dependencies]
pretty_assertions = "1.0.0"
