[package]
name = "documentation-builder"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2018"

[dependencies]
roxmltree = "0.14.1"
flate2 = "1.0.20"
tar = "0.4.37"
reqwest = "0.11.4"
itertools = "0.10.1"
lsp-asm = { path = "../lsp" }
serde_json = "1.0.66"
serde = { version = "1.0.127", features = ["derive"] }
directories = "3.0.2"
log = "0.4.14"

[dev-dependencies]
pretty_assertions = "0.7.2"
