[package]
name = "documentation-builder"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2018"

[dependencies]
roxmltree = "0.13.0"
flate2 = "1.0"
tar = "0.4"
reqwest = "0.10.8"
itertools = "0.10.1"
lsp-asm = { path = "../lsp" }
serde_json = "1.0.34"
serde = { version = "1.0.83", features = ["derive"] }
directories = "3.0.2"
log = "0.4"

[dev-dependencies]
pretty_assertions = "0.7.2"