[package]
name = "arch"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
parser = { path = "../parser" }
itertools = "0.11.0"
phf = { version = "0.11.2", features = ["macros"] }
phf_macros = { version = "0.11.2", features = ["unicase"] }
unicase = "2.6.0"
