[package]
name = "xtask"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2021"

[dependencies]
pretty_env_logger = "0.4.0"
clap = "2.34.0"
tokio = { version = "1.15.0", features = ["full"] }
documentation-builder = { path = "../crates/documentation-builder" }
