[package]
name = "xtask"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2018"

[dependencies]
pretty_env_logger = "0.4.0"
clap = "2.33.3"
tokio = { version = "1.10.0", features = ["full"] }
documentation-builder = { path = "../crates/documentation-builder" }
