[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
syntax = { path = "../syntax" }
nom = "7.1.0"
rowan = "0.15.0"
either = "1.6.1"
log = "0.4.14"

[dev-dependencies]
pretty_assertions = "1.0.0"
