[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
syntax = { path = "../syntax" }
nom = "7.1.1"
rowan = "0.15.10"
either = "1.8.0"
log = "0.4.17"
phf = "0.11.1"
unicase = "2.6.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
