[package]
name = "lsp-asm"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2018"

[[bin]]
name = "lsp-asm"
path = "src/bin/main.rs"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
lazy_static = "1.4.0"
regex = "1.5.3"
either = "1.6.1"
lsp-server = "0.4.1"
lsp-types = { version = "0.85.0", features = ["proposed"] }
serde_json = "1.0.34"
serde = { version = "1.0.83", features = ["derive"] }
nom = "5.0.0"
rowan = "0.12.6"
bitflags = "1.2.1"

symbolic = { version = "8.2.1", features = ["demangle"] }

[dev-dependencies]
pretty_assertions = "0.7.2"
