[package]
name = "lsp-asm"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2018"

[[bin]]
name = "lsp-asm"
path = "src/bin/main.rs"

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"
lazy_static = "1.4.0"
tokio = { version = "1.10.0", features = ["rt-multi-thread", "sync"] }
regex = "1.5.4"
either = "1.6.1"
lsp-server = "0.5.2"
lsp-types = { version = "0.89.2", features = ["proposed"] }
serde_json = "1.0.66"
serde = { version = "1.0.127", features = ["derive"] }
nom = "6.0.0"
rowan = "0.12.6"
itertools = "0.10.1"
directories = "3.0.2"
bitflags = "1.3.2"
rayon = "1.5.1"
once_cell = "1.8.0"
symbolic = { version = "8.3.0", features = ["demangle"] }
byte-unit = { version = "4.0.12", features = ["serde"] }

[dev-dependencies]
pretty_assertions = "0.7.2"

[features]
default = []
poison = []
