[package]
name = "lsp-asm"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2021"

[[bin]]
name = "lsp-asm"
path = "src/bin/main.rs"

[dependencies]
base = { path = "../base" }
syntax = { path = "../syntax" }
parser = { path = "../parser" }
documentation = { path = "../documentation" }
arch = { path = "../arch" }
fmt = { path = "../fmt" }
log = "0.4.17"
pretty_env_logger = "0.4.0"
lazy_static = "1.4.0"
tokio = { version = "1.19.2", features = ["rt-multi-thread", "sync"] }
regex = "1.5.6"
either = "1.6.1"
lsp-server = "0.6.0"
lsp-types = { version = "0.93.0", features = ["proposed"] }
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
toml = { version = "0.5.9", default-features = false }
rowan = "0.15.5"
itertools = "0.10.3"
rayon = "1.5.3"
once_cell = "1.12.0"
byte-unit = { version = "4.0.14", default-features = false, features = ["std", "serde"] }
shellwords = "1.1.0"
uuid = { version = "1.1.2", features = ["v4"] }
rustc-demangle = "0.1.21"
cpp_demangle = "0.3.5"
phf = { version = "0.10.1", features = ["macros"] }
phf_macros = { version = "0.10.0", features = ["unicase"] }
unicase = "2.6.0"
dissimilar = "1.0.4"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
