[package]
name = "lsp-asm"
version = "0.1.0"
authors = ["Jamie Cunliffe <Jamie.Cunliffe@outlook.com>"]
edition = "2018"

[[bin]]
name = "lsp-asm"
path = "src/bin/main.rs"

[dependencies]
base = { path = "../base" }
syntax = { path = "../syntax" }
parser = { path = "../parser" }
documentation = { path = "../documentation" }
log = "0.4.14"
pretty_env_logger = "0.4.0"
lazy_static = "1.4.0"
tokio = { version = "1.12.0", features = ["rt-multi-thread", "sync"] }
regex = "1.5.4"
either = "1.6.1"
lsp-server = "0.5.2"
lsp-types = { version = "0.89.2", features = ["proposed"] }
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
rowan = "0.14.0"
itertools = "0.10.1"
rayon = "1.5.1"
once_cell = "1.8.0"
symbolic = { version = "8.3.0", features = ["demangle"] }
byte-unit = { version = "4.0.12", features = ["serde"] }
shellwords = "1.1.0"
uuid = { version = "0.8.2", features = ["v4"] }

[dev-dependencies]
pretty_assertions = "0.7.2"
