[package]
name = "documentation"
version = "0.1.0"
edition = "2018"

[dependencies]
base = { path = "../base" }
syntax = { path = "../syntax" }
parser = { path = "../parser" }
itertools = "0.10.1"
serde_json = "1.0.66"
serde = { version = "1.0.127", features = ["derive"] }
directories = "3.0.2"
lazy_static = "1.4.0"

[features]
default = []
poison = []