[package]
name = "documentation"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
syntax = { path = "../syntax" }
parser = { path = "../parser" }
log = "0.4.14"
itertools = "0.10.1"
serde_json = "1.0.71"
serde = { version = "1.0.130", features = ["derive"] }
directories = "4.0.1"
lazy_static = "1.4.0"
either = { version = "1.6.1", features = ["serde" ] }
phf = { version = "0.10", features = ["macros"] }
phf_macros = { version = "0.10", features = ["unicase"] }
unicase = "2.6.0"

[dev-dependencies]
pretty_assertions = "1.0.0"

[features]
default = []
poison = []
