[package]
name = "documentation"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
syntax = { path = "../syntax" }
parser = { path = "../parser" }
itertools = "0.10.1"
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
directories = "4.0.1"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "0.7.2"

[features]
default = []
poison = []
