[package]
name = "documentation"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
syntax = { path = "../syntax" }
parser = { path = "../parser" }
arch = { path = "../arch" }
log = "0.4.17"
itertools = "0.10.3"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
directories = "4.0.1"
once_cell = "1.12.0"
either = { version = "1.6.1", features = ["serde" ] }
phf = { version = "0.10.1", features = ["macros"] }
phf_macros = { version = "0.10.0", features = ["unicase"] }
unicase = "2.6.0"

[dev-dependencies]
pretty_assertions = "1.2.1"

[features]
default = []
poison = []
