[package]
name = "base"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.14"
serde = { version = "1.0.127", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.5.4"
bitflags = "1.3.2"