[package]
name = "z-bdd-tests"
version = "0.1.0"
edition = "2021"

[[test]]
name = "bdd-tests"
path = "src/runner.rs"
harness = false

[dev-dependencies]
base = { path = "../base" }
documentation = { path = "../documentation", features = ["poison"] }
lsp-asm = { path = "../lsp" }
cucumber = "0.13.0"
tokio = { version = "1.19.2", default-features = false, features = ["macros", "rt-multi-thread"] }
lsp-types = { version = "0.93.0", features = ["proposed"] }
lsp-server = "0.6.0"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
pretty_assertions = "1.2.1"
async-trait = "0.1.56"
pretty_env_logger = "0.4.0"
parking_lot = "0.12.1"
itertools = "0.10.3"
