[package]
name = "bdd-tests"
version = "0.1.0"
edition = "2018"

[[test]]
name = "bdd-tests"
path = "src/runner.rs"
harness = false

[dev-dependencies]
lsp-asm = { path = "../lsp", features = ["poison"] }
cucumber_rust = { version = "0.8.4", features = ["macros"] }
tokio = { version = "1.10.0", features = ["macros", "rt-multi-thread"] }
lsp-types = { version = "0.89.2", features = ["proposed"] }
lsp-server = "0.5.2"
serde_json = "1.0.66"
serde = { version = "1.0.127", features = ["derive"] }
pretty_assertions = "0.7.2"
